baseURL = ""
disqusShortname = "revolve"
languageCode = "en-us"
paginate = 8
summaryLength = "10"
theme = "revolve-hugo"
title = "Revolve | Hugo Blog Template"
[[menu.main]]
URL = "/über-mich"
name = "Über mich"
weight = 1
[[menu.main]]
URL = "/kontakt"
name = "Kontakt"
weight = 2
[[menu.footer]]
URL = "/impressum"
name = "Impressum"
weight = 3
[[menu.footer]]
URL = "/datenschutz"
name = "Datenschutz"
weight = 4
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
contactFormAction = "#"
copyright = "Ralph Binder Public Relations 2020"
description = "Online-Magazin über Camping, Caravaning, Wohnwagen, Wohnmobile und Campingplätze"
googleAnalitycsID = "Your ID"
home = "Startseite"
logo = "/images/200522_LogoSchirm_transparent.png"
[params.author]
bio = "Unsere Reiseberichte erzählen vom Camping- und Caravaning-Urlaub in Europas schönsten Reisezielen und von den besten Campingplätzen in den entsprechenden Regionen."
designation = "Caravaning Reisen"
image = "/images/author.png"
name = "Ralph Binder"
signature = ""
[params.newsletter]
subtitle = "Subscribe my Newsletter for new blog posts , tips and info."
title = "Subscribe Newsletter"
[[params.plugins.css]]
URL = "/plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "/plugins/slick/slick.css"
[[params.plugins.css]]
URL = "/plugins/slick/slick-theme.css"
[[params.plugins.css]]
URL = "/plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "/plugins/magnific-popup/magnific-popup.css"
[[params.plugins.js]]
URL = "/plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "/plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "/plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "/plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
URL = "/plugins/magnific-popup/magnific-popup.js"
[[params.plugins.js]]
URL = "/plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "/plugins/search/mark.js"
[[params.plugins.js]]
URL = "/plugins/search/search.js"
[[params.plugins.js]]
URL = "/plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/CaravaningReisen/"
title = "facebook"
